FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
      build-essential \
      clang \
      curl \
      git \
      jq \
      libtool \
      python3 \
      sudo \
      vim \
      wget \
      zlib1g-dev
